language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: heroku
  api_key:
    secure: Y8jh5kz7Hmfudy0Mt74CEjHTK58DXeAZHffVtGHu40CfCAovprkKRjdswzeoAUWhVEgpXhNfxafpsurBZaXzO818mZTGp2oMCQZesNfoxvYnaXaJ6sfDndaJrUAlP0TsK8fUurUjsMts74WO718aS7oR8tg+MrMFrVOGKbGdLwlMBJfVlksII+A0enUaxjQ1I5sd3vdZWMdXwjidKUBRJEV7VUO0wURQVuErS4R34L+Tel53jdDbKrZc0dKaEH8s+J3lBOlhpJ66X4nxwoPKsXVPRK7oh9ytoW7ubqEuoj1EMltNZLh/YkXBLf6ir4UCD/t2+1XaEqPFwkaFgKnxAlx5Vwx/nVqbYRSwzWHzlt7Gy88gCETSsc7DGw6ew1e3lZh7BqjoUkchcAT4bwXTid4pQRLH+hORvLz56KMHYVxwhAL6YN60PUsSvIUJGCcoRLcFm3ciTQj+6mJNtm5H2KLf/vegSYKW8WrVqLHUeY+TFojqVPFcsNzQpM9AhWS2DCvuwzeEnjgfRhf7uylIZtrsdgsNP/ET4y8djZh+ZQE64BFS19IcxwJrN/kbK23IXNu+wjNutuScxaI5kawTqF9tLGI5fUiidN2PJhnjEntRnI5RaUJQ0T/rWq5RXGk9LFU1zAiXFA5xTBE6JCwrRjP1ucz2KHK6BupFUq24uxY=
  app: blogilista
  on:
    repo: josefinreuter/BlogApp 
