language: node_js
node_js:
- 8.11.1
before_script:
- cd ./blogilista
- npm install
env:
- TEST_MONGODB_URI=mongodb://admin:adm1nadm1n@ds259361.mlab.com:59361/blogilistadb-test
 global:
  secure: R4IAje3IeQ2ONuWzNjPOaOCkBnkWA2w9MUP3lmUJK5dWYP/LTAcp/4WXHlVYlRfynpVkn+fy91NhJoQw+/IDmMplTmJi7NL65n3+cYfcK6CQ7VlLgdrUZje3WVZLPUmCQw0Er3dtgDEU41K9LRPbFQ5c8KL0mIwdMXk88xPQ6nRC4R4Bymk35i5F1ftRhKoi53W9uew0yDqft/Lc7d+2RRnmBLQ6V+3XkWwgbtXOSQjcHsmQ6SY/ff6xhdAcsj+VpD+W5K0qin1wUE91a1nfW4DmeY30aC7o5adYqu7TfZsCXgfyzOLEPzGPotmoz2DVGTz3Ts8MZWTFtMkFAHXT/lastj9amrElTp76camUdY/P/CqxDk+O1N3mV8QU0vYdqSxjdPLc5l7srEI/Hk7Cy9jDr9rP2mqiKO1ijhX5YrxeHwO0q8UGNGIb+PS80WEEaT8YbFz+7XYJUpU6zb6SGXKNnJYkzaLkZza7ZlONNoxCnPMT/DIgUya13vzN94a0LhE6NG9kN5AvwTK4yPEcEYCmOcaVZK4Zve7gk7b4SeE5oyYdhfBinBRcJiZq0wCe6DSWyjGWjeIJ5ku28+niaFFQ8MYMHTvKsab+TonYCjyX6+9yFgpxoPESV/ilQwRTuu9ypd1D5VlmeWk3/SwOqWuz5GxsITegMy74XHGL8CQ=

script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: R4IAje3IeQ2ONuWzNjPOaOCkBnkWA2w9MUP3lmUJK5dWYP/LTAcp/4WXHlVYlRfynpVkn+fy91NhJoQw+/IDmMplTmJi7NL65n3+cYfcK6CQ7VlLgdrUZje3WVZLPUmCQw0Er3dtgDEU41K9LRPbFQ5c8KL0mIwdMXk88xPQ6nRC4R4Bymk35i5F1ftRhKoi53W9uew0yDqft/Lc7d+2RRnmBLQ6V+3XkWwgbtXOSQjcHsmQ6SY/ff6xhdAcsj+VpD+W5K0qin1wUE91a1nfW4DmeY30aC7o5adYqu7TfZsCXgfyzOLEPzGPotmoz2DVGTz3Ts8MZWTFtMkFAHXT/lastj9amrElTp76camUdY/P/CqxDk+O1N3mV8QU0vYdqSxjdPLc5l7srEI/Hk7Cy9jDr9rP2mqiKO1ijhX5YrxeHwO0q8UGNGIb+PS80WEEaT8YbFz+7XYJUpU6zb6SGXKNnJYkzaLkZza7ZlONNoxCnPMT/DIgUya13vzN94a0LhE6NG9kN5AvwTK4yPEcEYCmOcaVZK4Zve7gk7b4SeE5oyYdhfBinBRcJiZq0wCe6DSWyjGWjeIJ5ku28+niaFFQ8MYMHTvKsab+TonYCjyX6+9yFgpxoPESV/ilQwRTuu9ypd1D5VlmeWk3/SwOqWuz5GxsITegMy74XHGL8CQ=
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master
  strategy: git
