language: node_js
node_js:
- 8.11.1
env:
- TEST_MONGODB_URI=mongodb://admin:adm1nadm1n@ds259361.mlab.com:59361/blogilistadb-test
before_install:
- cd ./blogilista
before_script:
- npm install
script:
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: iP+qYW0wvA2K+T6bN7D8sTNoJNt2sWLvzqi+AWvAQAUaxjfRGvnGk6EZjyVEkXrDFw1yUQgza8WQl99Xvsm1l9wxC9Xi+4bqknPSDQBw8ZT1oqMOYscxVHfujbUC6kpyiMwTvIcrfh8SiXdoFTOI6bAieCWE9nZUlmY2gn6SSns9j8OwP0j7Fwl7RhiqtFHtTQ5At80fmhBE/KrX6O/lMOkhbmGYE/h39wPpdgcf12vrfl8nM5isli6lnwmWThJ1u9wusPtd4Q/NKAEp7v2/B1izg7BiwO6fwqRrLPbecob/jEBqXfpxX5BgyQUolyoZk9dpmBC51x6q7wY+Kkb0X0NvKjtuXUMuN31NfE683OuOu09GmtCcpJsjNYcpQKCGvikLzyWemynrMbMDKULLPB02bktWTJu1QaXhtK48gPNUZYtOSr0JO8l98Wv9aDjcOqjY/mbb/gfTCmvGvz7cp1cSrzcdzfA/xOi+RL0vvGfGoQ0PgOydAsatvvqOdjKOVbqzuY7OiUllt+epipYop0ecJ5QTYxBUn0ZsKPafG+KOE+GVlO7ssVtFr3DqKTQeGevwUZcUvIhlRKCuWIKzTBSF1hQzwdbD5Smzg9QP/LOMDeqburhgNGeObN36CDjFpalATaJos0RvH+vMyOpc1mtyJvkrco9czFyfSurjpFc=
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master
