language: node_js
node_js:
- 8.11.1
env:
- TEST_MONGODB_URI=mongodb://admin:adm1nadm1n@ds259361.mlab.com:59361/blogilistadb-test
before_install:
- cd ./blogilista
before_script:
- npm install
script:
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: fW25fIY8e1khj1oVIU44DAkn57tEHxjaRhHaA2BM8cOZcfFw9bYQv+gIC/IOqqzyZ3uRGix5Lt5MtTV1QBveEpLPHbnN7U5UzGqNfvWPMAAQFeygUowX+YgqA+eq2T+Ga3bTNVi3DBCOx0m4UVk/u41vwwRS63LlJ38RhDwYX10mjE5dUiW9LoOKbwtLaCw+NKHlezCOlbukjd/5QTIRnhInqYOl+4G6Pj7SRYPJzML+YaJepOAf/+BFdJOZGr8zBp86cS57fZVHIXqEOb1cLgsUhySvZzyFFfdC7Vk9rKJn2bhk+Y+df57nVVF0WWZXfSYiLsc78WBpZN4ySIvoqeKvSKJztGP8mAKPujBuoYY+54PjQUcwTaKNii/6cGMd+/B0fKzJz940FjMsPnWMIxPOnJ+wL3rfKQ3IGFehaWG3mYo+8Y3rohX1TsFKfvjw2S0VQSzavII8kMopY5OLZLqgy9HNy/BCe3oCS2LWSTvWVCpyK7lJ3ztWy9Vv09Vxibk+h0DRhyiIEQ6USVgL3EYV7rN+VrivIAI8P6NtGMWAPYu0c3pvkMDJGnnlC7tr7Onhjd6idio9mWClPcve0mJ4032janjQyz4uCbGZEd2/M7jntVs0Y8PNWTaDNsRM/3cNLXNhLx4lHaxLhOkOmJm0b7lJieBZHmEPfyju2H0=
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master
