language: node_js
node_js:
- 8.11.1
before_script:
- cd ./blogilista
- npm install
env:
- TEST_MONGODB_URI=mongodb://admin:adm1nadm1n@ds259361.mlab.com:59361/blogilistadb-test
script:
- npm run test
before_deploy:
- cd ..
deploy:
  provider: heroku
  api_key: rcQPO_6iTGRDVClZqXaNWQ
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master
