language: node_js
node_js:
- 8.11.1
before_install:
- cd ./blogilista
script:
- ./deploy-frontend.sh
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: WjNATuJW54r2/0FiEf6PEkg/SFH+O7rW0z9cjUHMh1E80Ds5hckEWo57n12d3jbrvyxDf8TqeClvFX8ToUg/CYEu/wS30zxzCFXHUBMC8k+N7f1chOWKDiAf8fAN4UneZoXs204de8VZQHuDPypwl/wNKQnATLllmLOfE+C2DZbNW1GxFEB+Ju8FKZYq5zhXlWFw3m3D0boyfNtVHeiSHJu4f8yrSKIjbz74SN2MZ0JLSOlYAFL/3E6pEboD3GKehd8ynB5CsZ9mvNFpZozhvQZ7L1RhkeCmCyyc3tXDJSiwW1Mf70X5yg2jmgvj6+QIyH7rBlJ6aW7ZMEo/keeSh+YUX6owIbfmXY8moVuLnIXDkgLkOr56BgFhrGVYSeFxluc2LLA9iGhFDHwhEow3JxKoF4hlSpIC6zG3SwCdzpNPypwetxhOs29gLs1fh76+dTx4kRAt4/T/e5NbG5sZvpgY45+izoC8oRE1yHBzpYRmGS37uhx/pvmLl0k0U0wkjUYSvKiVzr5WYRTfvvXmhjkURGYMUm4SJoKUJ3QZXXTJ5mLat+vf3k9vB58uN9McmVny+a/fwFSSujrPmcVip6hh76sEGFDGRqNY+Ka3bEHZnEw6XBdRpiGfX7+bkx4wffJ4+P/J2Z+2pte3yQ+TzQlcbKKBN9JMs+D4ufDGWUk=
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master
