language: node_js
node_js:
  - 8.11.1

before_script:
  - cd ./blogilista
  - npm install

env:
  - TEST_MONGODB_URI=mongodb://admin:adm1nadm1n@ds259361.mlab.com:59361/blogilistadb-test
  - MONGODB_URI=mongodb://admin:adm1nadm1n@ds125422.mlab.com:25422/blogilistadb-dev
  - PORT=3001
  - TEST_PORT=3002
  - SECRET=salainen
  
script:
  - npm run test

deploy:
  provider: heroku
  api_key: 
    secure: Y8jh5kz7Hmfudy0Mt74CEjHTK58DXeAZHffVtGHu40CfCAovprkKRjdswzeoAUWhVEgpXhNfxafpsurBZaXzO818mZTGp2oMCQZesNfoxvYnaXaJ6sfDndaJrUAlP0TsK8fUurUjsMts74WO718aS7oR8tg
  app: blogilista
  on:
    repo: josefinreuter/BlogApp
    branch: master